# Site settings
title: Global Digital Humanities Symposium
email: dh@msu.edu
description: "Global Digital Humanities Symposium, April 8–9 at Michigan State University"
baseurl: "/globaldh2016"
url: "msudh.github.io/globaldh2016"
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown
permalink: pretty
