# Site settings
title: Global Digital Humanities Symposium
email: dh@msu.edu
description: "April 8–9 at Michigan State University"
baseurl: ""
url: "http://msuglobaldh.org/"
twitter_username: "#msuglobaldh"
#github_username:  ""

# Build settings
markdown: kramdown
permalink: pretty
